//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIWEBAPI.SystemResource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MailResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDIWEBAPI.SystemResource.MailResource", typeof(MailResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      
        ///      /* Default CSS */
        ///      body,#body_style {margin: 0; padding: 0; background: #f1f1f1; color: #5b656e;}
        ///      a {color: #09c;}
        ///      a img {border: none [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrochureTemplate {
            get {
                return ResourceManager.GetString("BrochureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html
        ///	xmlns=&quot;http://www.w3.org/1999/xhtml&quot;
        ///	xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///	xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///		&lt;meta name=&quot;x-apple-disable-message-reformatting&quot; /&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///		&lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrochureTemplate2 {
            get {
                return ResourceManager.GetString("BrochureTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Нууц үг сэргээх&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-fa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgetPass {
            get {
                return ResourceManager.GetString("ForgetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  BEGIN:VCALENDAR
        ///PRODID:-//Microsoft Corporation//Outlook 14.0 MIMEDIR//EN
        ///VERSION:2.0
        ///METHOD:REQUEST
        ///X-MS-OLK-FORCEINSPECTOROPEN:TRUE
        ///BEGIN:VTIMEZONE
        ///TZID:Ulaanbaatar Standard Time
        ///BEGIN:STANDARD
        ///DTSTART:{Dates}
        ///RRULE:FREQ=YEARLY;BYDAY=-1FR;BYMONTH=9
        ///TZOFFSETFROM:+0900
        ///TZOFFSETTO:+0800
        ///END:STANDARD
        ///BEGIN:DAYLIGHT
        ///DTSTART:16010331T020000
        ///RRULE:FREQ=YEARLY;BYDAY=-1SA;BYMONTH=3
        ///TZOFFSETFROM:+0800
        ///TZOFFSETTO:+0900
        ///END:DAYLIGHT
        ///END:VTIMEZONE
        ///BEGIN:VEVENT
        ///ATTENDEE;CN={MailTo};RSVP=TRUE:{MailT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ICalendar {
            get {
                return ResourceManager.GetString("ICalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;&lt;title&gt;Бизнес өртөө&lt;/title&gt;&lt;style&gt;
        ///		  /* -------------------------------------
        ///			  GLOBAL RESETS
        ///		  ------------------------------------- */
        ///		  img {
        ///			border: none;
        ///			-ms-interpolation-mode: bicubic;
        ///			max-width: 100%; }
        ///
        ///		  body {
        ///			background-color: #f6f6f6;
        ///			font-family: sans-serif;
        ///			-webkit-font-smoothing: antialiased;
        ///			font-siz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseRequest {
            get {
                return ResourceManager.GetString("LicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MassMail {
            get {
                return ResourceManager.GetString("MassMail", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MassMail1
        {
            get
            {
                return ResourceManager.GetString("MassMail1", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;it&quot;&gt;&lt;head&gt;
        ///&lt;title&gt;Urto&lt;/title&gt;
        ///&lt;!--
        ///
        ///
        ///COLORE INTENSE  #9C010F
        ///COLORE LIGHT #EDE8DA
        ///
        ///TESTO LIGHT #3F3D33
        ///TESTO INTENSE #ffffff
        ///
        ///
        /// --&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///$red: #e74c3c;
        ///
        ///      #ko_onecolumnBlock_4 .textintenseStyle a, #ko_onecolumnBlock_4 .textintenseStyle a:link, #ko_onecolumnBlock_4 .textintenseStyle a:visited, #ko_onecolumnBlock_4 .textintenseStyle a:hover{
        ///        color: #fffff [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MasterConfirm {
            get {
                return ResourceManager.GetString("MasterConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;it&quot;&gt;&lt;head&gt;
        ///&lt;title&gt;Urto&lt;/title&gt;
        ///&lt;!--
        ///
        ///
        ///COLORE INTENSE  #9C010F
        ///COLORE LIGHT #EDE8DA
        ///
        ///TESTO LIGHT #3F3D33
        ///TESTO INTENSE #ffffff
        ///
        ///
        /// --&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///$red: #e74c3c;
        ///
        ///      #ko_onecolumnBlock_4 .textintenseStyle a, #ko_onecolumnBlock_4 .textintenseStyle a:link, #ko_onecolumnBlock_4 .textintenseStyle a:visited, #ko_onecolumnBlock_4 .textintenseStyle a:hover{
        ///        color: #fffff [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MasterNote {
            get {
                return ResourceManager.GetString("MasterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;it&quot;&gt;&lt;head&gt;
        ///&lt;title&gt;Urto&lt;/title&gt;
        ///&lt;!--
        ///
        ///
        ///COLORE INTENSE  #9C010F
        ///COLORE LIGHT #EDE8DA
        ///
        ///TESTO LIGHT #3F3D33
        ///TESTO INTENSE #ffffff
        ///
        ///
        /// --&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///$red: #e74c3c;
        ///
        ///      #ko_onecolumnBlock_4 .textintenseStyle a, #ko_onecolumnBlock_4 .textintenseStyle a:link, #ko_onecolumnBlock_4 .textintenseStyle a:visited, #ko_onecolumnBlock_4 .textintenseStyle a:hover{
        ///        color: #fffff [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MasterRequest {
            get {
                return ResourceManager.GetString("MasterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;it&quot;&gt;&lt;head&gt;
        ///&lt;title&gt;Urto&lt;/title&gt;
        ///&lt;!--
        ///
        ///
        ///COLORE INTENSE  #9C010F
        ///COLORE LIGHT #EDE8DA
        ///
        ///TESTO LIGHT #3F3D33
        ///TESTO INTENSE #ffffff
        ///
        ///
        /// --&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///$red: #e74c3c;
        ///
        ///      #ko_onecolumnBlock_4 .textintenseStyle a, #ko_onecolumnBlock_4 .textintenseStyle a:link, #ko_onecolumnBlock_4 .textintenseStyle a:visited, #ko_onecolumnBlock_4 .textintenseStyle a:hover{
        ///        color: #fffff [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MasterStatus {
            get {
                return ResourceManager.GetString("MasterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;it&quot;&gt;&lt;head&gt;
        ///&lt;title&gt;Urto&lt;/title&gt;
        ///&lt;!--
        ///
        ///
        ///COLORE INTENSE  #9C010F
        ///COLORE LIGHT #EDE8DA
        ///
        ///TESTO LIGHT #3F3D33
        ///TESTO INTENSE #ffffff
        ///
        ///
        /// --&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///$red: #e74c3c;
        ///
        ///      #ko_onecolumnBlock_4 .textintenseStyle a, #ko_onecolumnBlock_4 .textintenseStyle a:link, #ko_onecolumnBlock_4 .textintenseStyle a:visited, #ko_onecolumnBlock_4 .textintenseStyle a:hover{
        ///        color: #fffff [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewDevice {
            get {
                return ResourceManager.GetString("NewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewUserGuide {
            get {
                return ResourceManager.GetString("NewUserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewUserTemplate {
            get {
                return ResourceManager.GetString("NewUserTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderTemplate {
            get {
                return ResourceManager.GetString("OrderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentCancelTemplate {
            get {
                return ResourceManager.GetString("PaymentCancelTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentMassTemplate
        {
            get
            {
                return ResourceManager.GetString("PaymentMassTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentTemplate {
            get {
                return ResourceManager.GetString("PaymentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleEmailTemplate {
            get {
                return ResourceManager.GetString("SampleEmailTemplate", resourceCulture);
            }
        }


        /// <summary>
        ///    Looks up a localized string similar to  &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Бизнес өртөө&lt;/title&gt;
        ///    &lt;style&gt;
        ///      /* -------------------------------------
        ///          GLOBAL RESETS
        ///      ------------------------------------- */
        ///      img {
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///        max-width: 100%; }
        ///
        ///      body {
        ///        background-color: #f6f6f6;
        ///        font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Production1
        {
            get
            {
                return ResourceManager.GetString("Production1", resourceCulture);
            }
        }


        public static string MasterRequestSingle
        {
            get
            {
                return ResourceManager.GetString("MasterRequestSingle", resourceCulture);
            }
        }
    }
}
