//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIWEBAPI.SystemResource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MessageResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDIWEBAPI.SystemResource.MessageResource", typeof(MessageResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to #orderdate udriin #storename hypermarket zahialga ilgeelee. #shorturl
        /// Zahialgiin huudas deerh baraa bolon uniig shalgana uu?
        ///.
        /// </summary>
        public static string OrderMessage {
            get {
                return ResourceManager.GetString("OrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to #orderdate udriin #storename hypermarket butsaaltiin medeelliig ilgeelee. #shorturl
        ///Butsaaltiig zaasan hugatsaanii dotor avahiig husye?.
        /// </summary>
        public static string ReturnOrderMessage {
            get {
                return ResourceManager.GetString("ReturnOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to tanai companii butsaalt ni #storename hypermarketiin ustgah baraanii jagsaaltad orson tul yaraltai butsaan avna uu!
        ///#shorturl.
        /// </summary>
        public static string ReturnOrderMessage2 {
            get {
                return ResourceManager.GetString("ReturnOrderMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tanai companaas #storename hypermarket-d niiluuldeg daraah baraag gereend zaagdsan E-4 zaaltiin daguu ustgasan bolno.
        ///#shorturl.
        /// </summary>
        public static string ReturnOrderMessage3 {
            get {
                return ResourceManager.GetString("ReturnOrderMessage3", resourceCulture);
            }
        }
    }
}
